version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/node:12.18

    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}
            - node-v1-

      - run: yarn install --frozen-lockfile

      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn lint
      - run: yarn test
